[package]
name = "dipl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_mod_picking = "0.7"
bevy_transform_gizmo = "0.2"